In [1]:
import numpy as np

In [2]:
lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [3]:
ar = np.array(lst)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
ar2 = np.arange(0, 1001, 5)
ar2

array([   0,    5,   10,   15,   20,   25,   30,   35,   40,   45,   50,
         55,   60,   65,   70,   75,   80,   85,   90,   95,  100,  105,
        110,  115,  120,  125,  130,  135,  140,  145,  150,  155,  160,
        165,  170,  175,  180,  185,  190,  195,  200,  205,  210,  215,
        220,  225,  230,  235,  240,  245,  250,  255,  260,  265,  270,
        275,  280,  285,  290,  295,  300,  305,  310,  315,  320,  325,
        330,  335,  340,  345,  350,  355,  360,  365,  370,  375,  380,
        385,  390,  395,  400,  405,  410,  415,  420,  425,  430,  435,
        440,  445,  450,  455,  460,  465,  470,  475,  480,  485,  490,
        495,  500,  505,  510,  515,  520,  525,  530,  535,  540,  545,
        550,  555,  560,  565,  570,  575,  580,  585,  590,  595,  600,
        605,  610,  615,  620,  625,  630,  635,  640,  645,  650,  655,
        660,  665,  670,  675,  680,  685,  690,  695,  700,  705,  710,
        715,  720,  725,  730,  735,  740,  745,  7

In [12]:
ar3 = np.zeros(100)
ar3

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [31]:
lst2 = [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]
ar4 = np.array(lst2)
ar5 = ar4.reshape(1, 12)
print(ar4.reshape(12, 1))
print(ar5.shape)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]
(1, 12)


In [39]:
lst1 = [1, 2, 3]
lst2 = [4, 5, 6]
ar1 = np.array(lst1)
ar2 = np.array(lst2)
ar3 = ar1 * ar2
ar3

array([ 4, 10, 18])

In [ ]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# ضرب دو ماتریس
C = np.dot(A, B)
print("Matrix Multiplication:\n", C)

Matrix Multiplication:
 [[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


: 